services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics
    volumes:
      - pg_data:/var/lib/postgresql/data

  #  clickhouse:
  #    image: clickhouse/clickhouse-server:23.4
  #    ports:
  #      - "8123:8123"   # HTTP
  #      - "9000:9000"   # Native TCP
  #    ulimits:
  #      nofile:
  #        soft: 262144
  #        hard: 262144
  #    volumes:
  #      - clickhouse_data:/var/lib/clickhouse
  #    environment:
  #      CLICKHOUSE_DB: analytics
  #
  #  connect:
  #    image: debezium/connect:2.6
  #    depends_on:
  #      - kafka
  #      - postgres
  #    ports:
  #      - "8083:8083"
  #    environment:
  #      BOOTSTRAP_SERVERS: kafka:9092
  #      GROUP_ID: 1
  #      CONFIG_STORAGE_TOPIC: debezium_connect_config
  #      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
  #      STATUS_STORAGE_TOPIC: debezium_connect_statuses
  #      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  #      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  #      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
  #      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
  #      CONNECT_REST_ADVERTISED_HOST_NAME: connect
  #      CONNECT_PLUGIN_PATH: /kafka/connect,/debezium-plugins
  #    volumes:
  #      - ./plugins:/debezium-plugins

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9001:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092

volumes:
  pg_data:
  clickhouse_data:
